// Domain model layer for AlarmX (schema v1).
//
// MODEL DECISION (deliberate, not an omission): the entity classes
// (`Alarm`, `Mission`, `AlarmHistoryData`, `AppSetting`) are the immutable
// row classes generated by Drift in `lib/core/database/*.g.dart`. They already
// satisfy every domain-model requirement — immutable fields, value equality,
// `copyWith`, and `toJson`/`fromJson` serialization — so a second hand-written
// model layer with mappers would be pure duplication in a project this size.
//
// What IS hand-written here is the *typed vocabulary* over the raw stored
// columns, so business logic never touches magic strings or ints:
//
//   - `RepeatType`    <-> `Alarms.repeatType`   (TEXT: 'once'/'daily'/'custom')
//   - `MissionType`   <-> `Missions.type`       (TEXT: 'none'/'math'/...)
//   - `AlarmResult`   <-> `AlarmHistory.result` (TEXT: 'ongoing'/'success'/...)
//   - `RepeatDays`    <-> `Alarms.repeatDays`   (INT bitmask 0..127)
//
// The repositories translate between these types and the stored columns at
// the boundary. If a future schema version moves the conversion into Drift
// `TypeConverter`s, these enums stay the public vocabulary — only the mapping
// site changes.

export 'alarm_result.dart';
export 'mission_type.dart';
export 'repeat_days.dart';
export 'repeat_type.dart';
